name: Send Notify
inputs:
  category:
    description: "Message category"
    required: true
    example: "apply"
  env:
    description: "Target to deploy"
    required: true
    example: "DEV"
  version:
    description: "Version to deploy"
    required: true
    example: "2025.6.1"
  hook:
    description: "Hook to call"
    required: true
    example: "***"

runs:
  using: "composite"
  steps:
    - name: Generate DingTalk message
      id: message
      shell: bash
      run: |
        environment=""
        path=""
        
        if [ "${{ inputs.env }}" = "DEV" ]; then
          environment+="DEV(å¼€å‘çŽ¯å¢ƒ)"
          path+="dev.json"
        fi
        
        if [ "${{ inputs.env }}" = "STABLE" ]; then
          environment+="STABLE(ç”Ÿäº§çŽ¯å¢ƒ)"
          path+="stable.json"
        fi
        
        timestamp=$(TZ='Asia/Shanghai' date +"%Y-%m-%d %H:%M:%S%:z")
        
        if [ "${{ inputs.category }}" = "apply" ]; then
          local_version=$(jq -r '.supervisor' "$path")
          message_title="æ–°ç‰ˆæœ¬Supervisor-Deployå®¡æ‰¹é€šçŸ¥"
          message_body="---------------------------------------\n\n"
          message_body+="#### **ðŸ“Œ éƒ¨ç½²ä¿¡æ¯** \n\n"
          message_body+="- **çŽ¯å¢ƒç±»åž‹**:[ **$environment** ] \n\n"
          message_body+="- **éƒ¨ç½²ç»„ä»¶**:[ **Supervisor** ] \n\n"
          message_body+="- **å½“å‰ç‰ˆæœ¬**:[ **$local_version** ] \n\n"
          message_body+="- **éƒ¨ç½²ç‰ˆæœ¬**:[ **[${{ inputs.tag }}](https://github.com/iHost-Open-Source-Project/ha-supervisor/tree/ihost-${{ inputs.tag }})** ] \n\n"
          message_body+="---------------------------------------\n\n"
          message_body+="#### **ðŸ‘¤ å®¡æ‰¹å‘èµ·ä¿¡æ¯**  \n\n"
          message_body+="- **å‘èµ·äºº**:[ **${{ github.event.actor.name || github.actor }}** ] \n\n"
          message_body+="- **å‘èµ·æ—¶é—´**:[ **$timestamp** ] \n\n "
          message_body+="#### **ðŸ”— æ“ä½œå…¥å£**   \n\n"
          message_body+="- **âœ… å®¡æ‰¹é“¾æŽ¥**ï¼š**[ç‚¹å‡»è·³è½¬è‡³å®¡æ‰¹ç¡®è®¤é¡µ](https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }})** \n\n"
        fi
        if [ "${{ inputs.category }}" = "result" ]; then 
          message_title="Supervisor-Deployéƒ¨ç½²ç»“æžœé€šçŸ¥"
          message_body="---------------------------------------\n\n"
          message_body+="#### **ðŸ“Œ ${{ inputs.env }}çŽ¯å¢ƒéƒ¨ç½²ç»“æŸ** \n\n"
        fi
        
        
        echo "message_title=$message_title" >> $GITHUB_OUTPUT
        echo "message_body<<EOF" >> $GITHUB_OUTPUT
        echo "$message_body" >> $GITHUB_OUTPUT
        echo "EOF" >> $GITHUB_OUTPUT
        echo "message: $message_body"

    - name: Send DingTalk notification
      shell: bash
      id: send
      run: |
        message=$(cat <<EOF
        {
          "msgtype": "markdown",
          "markdown": {
            "title": "${{ steps.message.outputs.message_title }}",
            "text": "### âš™ï¸ **${{ inputs.env }}çŽ¯å¢ƒSupervisoréƒ¨ç½²å®¡æ‰¹ç”³è¯·**  \n\n ${{ steps.message.outputs.message_body }}"
          },
          "at": {
            "isAtAll": true
          }
        }
        EOF
        )
        
        response=$(curl -s -X POST "${{ inputs.hook }}" \
          -H "Content-Type: application/json" \
          -d "$message")